name: Build for Windows

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip

    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md"
          ARCHIVE_TYPES: ${{ matrix.archive }}
          MINIFY: "yes"

      # Step 6: Upload release asset
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
